services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - 27017:27017

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        - PORT=${PORT}
    environment:
      PORT: ${PORT}
      DB_HOST: mongodb
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      CODE_LIFE_TIME: ${CODE_LIFE_TIME}
      MONGO_URI: ${MONGO_URI}
      NODE_ENV: ${NODE_ENV}
    ports:
      - 8080:${PORT}
    depends_on:
      - mongodb

  devmx:
    build:
      context: .
      dockerfile: Dockerfile.front
    environment:
      PORT: ${PORT}
    ports:
      - 4200:4200
    depends_on:
      - server
      - mongodb
