type Arrow =
  | 'up'
  | 'down'
  | 'left'
  | 'right'
  | 'up-left'
  | 'up-right'
  | 'down-left'
  | 'down-right'
  | 'minimize'
  | 'repeat'
  | 'split'
  | 'switch'
  | 'left-up'
  | 'right-down'
  | 'right-up'
  | 'bar-up'
  | 'bar-right'
  | 'bar-down'
  | 'bar-left'
  | 'bar-up-alt'
  | 'bar-right-alt'
  | 'bar-down-alt'
  | 'bar-left-alt'
  | 'down-circle'
  | 'left-circle'
  | 'right-circle'
  | 'up-circle'
  | 'horizontal-expand'
  | 'vertical-expand'
  | 'vertical-maximize'
  | 'vertical-minimize';

export type ArrowIcon = `arrow/${Arrow}`;
