export type Building =
  | 'building-alt'
  | 'building'
  | 'church'
  | 'hospital-2'
  | 'hospital-3'
  | 'hospital'
  | 'house-2-alt'
  | 'house-2'
  | 'house-3-alt'
  | 'house-3'
  | 'house-alt'
  | 'house'
  | 'japanese-house'
  | 'school'
  | 'shop-2-alt'
  | 'shop-2'
  | 'shop-3-alt'
  | 'shop-3'
  | 'shop-4-alt'
  | 'shop-4'
  | 'shop-5'
  | 'shop-6'
  | 'shop-7'
  | 'shop-8'
  | 'shop'
  | 'skyscraper-2'
  | 'skyscraper-3'
  | 'skyscraper-4'
  | 'skyscraper'
  | 'v';

export type BuildingIcon = `building/${Building}`;
