export * from './arrow';
export * from './building';
export * from './doc';
export * from './e-commerce';
export * from './emoji';
export * from './icon';
export * from './menu';
export * from './software';
export * from './transport';
