import { createCode, createMail, hideEmail } from '@devmx/shared-util-data';
import { ResponseMessage, UseCase } from '@devmx/shared-api-interfaces';
import { Env, MailerService } from '@devmx/shared-api-interfaces/server';
import { AuthenticationError } from '@devmx/shared-util-errors';
import { UsersService } from '../services';

export class SendUserCodeUseCase implements UseCase<string, ResponseMessage> {
  constructor(
    private usersService: UsersService,
    private mailerService: MailerService,
    private env: Env
  ) {}

  async execute(name: string) {
    const user = await this.usersService.findOneBy('name', name);

    if (!user) {
      throw new AuthenticationError();
    }

    const code = { value: createCode(), timestamp: new Date() };

    await this.usersService.updateCode(user.id, code);

    const mail = createMail(
      user.contact.email,
      `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="pt"><head><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1" name="viewport"><meta name="x-apple-disable-message-reformatting"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="telephone=no" name="format-detection"><title>Cópia de (2) Empty template</title> <!--[if (mso 16)]><style type="text/css"> a {text-decoration: none;}  </style><![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><!--[if gte mso 9]><noscript> <xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> </noscript>
<![endif]--><!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i" rel="stylesheet"><!--<![endif]--><style type="text/css">.rollover:hover .rollover-first { max-height:0px!important; display:none!important;}.rollover:hover .rollover-second { max-height:none!important; display:block!important;}.rollover span { font-size:0px;}u + .body img ~ div div { display:none;}#outlook a { padding:0;}span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99;}a.es-button { mso-style-priority:100!important; text-decoration:none!important;}a[x-apple-data-detectors],#MessageViewBody a { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important;}.es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all;}
@media only screen and (max-width:600px) {.es-m-p20b { padding-bottom:20px!important } .es-p-default { } *[class="gmail-fix"] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } .es-header-body p { } .es-content-body p { } .es-footer-body p { } .es-infoblock p { } h1 { font-size:30px!important; text-align:left } h2 { font-size:24px!important; text-align:left } h3 { font-size:20px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:30px!important }
 .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:24px!important } .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important } .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px!important } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px!important } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px!important } .es-menu td a { font-size:14px!important } .es-header-body p, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body a { font-size:14px!important } .es-footer-body p, .es-footer-body a { font-size:14px!important } .es-infoblock p, .es-infoblock a { font-size:12px!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center!important }
 .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right!important } .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline!important } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0!important; font-size:0!important; display:block } .es-spacer { display:inline-table }
 a.es-button, button.es-button { font-size:18px!important; padding:10px 20px 10px 20px!important; line-height:120%!important } a.es-button, button.es-button, .es-button-border { display:inline-block!important } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block!important } .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important }
 table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } .h-auto { height:auto!important } .es-text-1835 .es-text-mobile-size-48, .es-text-1835 .es-text-mobile-size-48 * { font-size:48px!important; line-height:150%!important } .es-text-8031 .es-text-mobile-size-18, .es-text-8031 .es-text-mobile-size-18 * { font-size:18px!important; line-height:150%!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
 </head> <body class="body" style="width:100%;height:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0"><div dir="ltr" class="es-wrapper-color" lang="pt" style="background-color:#F6F6F6"><!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#f6f6f6"></v:fill> </v:background><![endif]--><table width="100%" cellspacing="0" cellpadding="0" class="es-wrapper" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#F6F6F6"><tr><td valign="top" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" align="center" class="es-content" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr>
<td align="center" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" align="center" bgcolor="#222" class="es-content-body" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#222222;width:600px" role="none"><tr><td align="left" data-custom-paddings="true" style="padding:0;Margin:0;padding-top:20px;padding-right:20px;padding-left:20px"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" valign="top" style="padding:0;Margin:0;width:560px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" style="padding:0;Margin:0;font-size:0px"><a target="_blank" href="https://devparana.mx" style="mso-line-height-rule:exactly;text-decoration:underline;color:#38B44D;font-size:14px"><img src="https://enetavj.stripocdn.email/content/guids/CABINET_8c9d6acbaee38ebf6fa01b547d804af726c15998862a112920c3cdfa98b8fe30/images/yearconf_2024_darktrue2x2.png" alt="" height="150" class="adapt-img" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td></tr></table></td></tr></table></td></tr><tr><td align="left" style="padding:0;Margin:0;padding-top:30px;padding-right:30px;padding-left:30px"><table cellpadding="0" cellspacing="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" valign="top" style="padding:0;Margin:0;width:540px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;padding-top:10px;padding-bottom:10px"><h2 style="Margin:0;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:24px;font-style:normal;font-weight:bold;line-height:28.8px;color:#FFFFFF">Aqui está seu código de acesso</h2></td></tr> <tr>
<td align="center" class="es-text-1835" style="padding:0;Margin:0;padding-top:20px;padding-bottom:20px"><h2 class="es-text-mobile-size-48" style="Margin:0;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:48px;font-style:normal;font-weight:bold;line-height:57.6px;color:#38b44d"><strong>${code.value}</strong></h2></td></tr><tr><td align="center" class="es-text-8031" style="padding:0;Margin:0;padding-top:10px;padding-bottom:10px"><p class="es-text-mobile-size-18" style="Margin:0;mso-line-height-rule:exactly;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;line-height:27px;letter-spacing:0;color:#FFFFFF;font-size:18px"><strong><u>Não compartilhe</u></strong> com ninguém, ele é pessoal e intransferível!</p></td></tr></table></td></tr></table></td></tr> <tr>
<td align="left" data-custom-paddings="true" style="padding:30px;Margin:0"><!--[if mso]><table style="width:540px" cellpadding="0" cellspacing="0"><tr><td style="width:93px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" class="es-m-p20b" style="padding:0;Margin:0;width:73px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" style="padding:0;Margin:0;font-size:0"><a target="_blank" href="https://devparana.mx" style="mso-line-height-rule:exactly;text-decoration:underline;color:#38B44D;font-size:14px"><img src="https://enetavj.stripocdn.email/content/guids/CABINET_8c9d6acbaee38ebf6fa01b547d804af726c15998862a112920c3cdfa98b8fe30/images/devmx_1.png" alt="DevParaná Experience" height="48" title="DevParaná Experience" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td></tr></table></td><td class="es-hidden" style="padding:0;Margin:0;width:20px"></td></tr></table> <!--[if mso]></td><td style="width:73px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr>
<td align="left" style="padding:0;Margin:0;width:73px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;font-size:0"><a target="_blank" href="https://devpr.org/whatsapp" style="mso-line-height-rule:exactly;text-decoration:underline;color:#38B44D;font-size:14px"><img height="48" src="https://enetavj.stripocdn.email/content/guids/CABINET_8c9d6acbaee38ebf6fa01b547d804af726c15998862a112920c3cdfa98b8fe30/images/9026159_whatsapp_logo_icon.png" alt="Comunidade WhatsApp DevParaná" title="Comunidade WhatsApp DevParaná" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td></tr></table></td><td class="es-hidden" style="padding:0;Margin:0;width:20px"></td></tr></table> <!--[if mso]></td>
<td style="width:73px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" style="padding:0;Margin:0;width:73px"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" style="padding:0;Margin:0;font-size:0"><a target="_blank" href="https://github.com/DeveloperParana" style="mso-line-height-rule:exactly;text-decoration:underline;color:#38B44D;font-size:14px"><img src="https://enetavj.stripocdn.email/content/guids/CABINET_8c9d6acbaee38ebf6fa01b547d804af726c15998862a112920c3cdfa98b8fe30/images/9111275_github_icon.png" alt="Github DevParaná" height="48" title="Github DevParaná" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td></tr></table></td><td class="es-hidden" style="padding:0;Margin:0;width:20px"></td></tr></table> <!--[if mso]></td><td style="width:73px" valign="top"><![endif]--><table cellspacing="0" align="left" cellpadding="0" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr>
<td align="left" class="es-m-p20b" style="padding:0;Margin:0;width:73px"><table width="100%" role="presentation" cellpadding="0" cellspacing="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;font-size:0"><a target="_blank" href="https://www.instagram.com/devparana" style="mso-line-height-rule:exactly;text-decoration:underline;color:#38B44D;font-size:14px"><img height="48" src="https://enetavj.stripocdn.email/content/guids/CABINET_8c9d6acbaee38ebf6fa01b547d804af726c15998862a112920c3cdfa98b8fe30/images/2959748_instagram_photo_share_icon.png" alt="Instagram DevParaná" title="Instagram DevParaná" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td></tr></table></td><td class="es-hidden" style="padding:0;Margin:0;width:20px"></td></tr></table> <!--[if mso]></td><td style="width:20px"></td>
<td style="width:74px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="left" class="es-left" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"><tr><td align="left" style="padding:0;Margin:0;width:74px"><table cellspacing="0" width="100%" role="presentation" cellpadding="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td align="center" style="padding:0;Margin:0;font-size:0"><a target="_blank" href="https://www.linkedin.com/company/83523870" style="mso-line-height-rule:exactly;text-decoration:underline;color:#38B44D;font-size:14px"><img alt="LinkedIn DevParaná" height="48" src="https://enetavj.stripocdn.email/content/guids/CABINET_8c9d6acbaee38ebf6fa01b547d804af726c15998862a112920c3cdfa98b8fe30/images/9111173_linkedin_icon.png" title="LinkedIn DevParaná" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td></tr></table></td></tr></table> <!--[if mso]></td><td style="width:20px"></td><td style="width:74px" valign="top"><![endif]--><table cellpadding="0" cellspacing="0" align="right" class="es-right" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right"><tr>
// <td align="left" style="padding:0;Margin:0;width:74px"><table cellpadding="0" cellspacing="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="center" style="padding:0;Margin:0;font-size:0"><a target="_blank" href="https://www.youtube.com/c/DevParana" style="mso-line-height-rule:exactly;text-decoration:underline;color:#38B44D;font-size:14px"><img height="48" src="https://enetavj.stripocdn.email/content/guids/CABINET_8c9d6acbaee38ebf6fa01b547d804af726c15998862a112920c3cdfa98b8fe30/images/2959742_broadcast_google_streaming_video_youtube_icon_SkF.png" alt="YouTube DevParaná" title="YouTube DevParaná" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a> </td></tr></table></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></td></tr></table></td></tr></table></div></body></html>`,
      `Código de autenticação`
    );

    if (this.env.production) {
      await this.mailerService.send(mail);
      return { message: `Enviado para ${hideEmail(user.contact.email)}` };
    } else {
      return { message: `Fala Dev! Usa esse código aqui: ${code.value}` };
    }
  }
}
