name: Build and deploy Node.js app to Azure Web App - devpr

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_front:
        description: 'Mark this checkbox to deploy and build the front-end'
        required: true
        default: false
        type: boolean

jobs:
  build-deploy-front:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.deploy_front == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout repository
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.1

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm exec nx run-many -t build --projects devmx --configuration=production --parallel 10

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/devmx/browser

  build-back:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://devmx.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_947982706eed46ce985090481ab47364 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_86f3c94c1b5143be904bfc1de2add431 }}
  
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: devmx.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_947982706eed46ce985090481ab47364 }}/devmx-server:${{ github.sha }}
          file: ./Dockerfile.server

  deploy:
    runs-on: ubuntu-latest
    needs: build-back
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devpr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_36a287a711bf47e6a54130170298549c }}
        images: 'devmx.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_947982706eed46ce985090481ab47364 }}/devmx-server:${{ github.sha }}'